name: pages-build-deployment

# 当 main 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    # 下载仓库代码
    - uses: actions/checkout@v2

    # 缓存依赖
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # 安装依赖
    - run: yarn

    # 打包构建
    - run: yarn build

    - run: git config --global user.email "1581647952@qq.com"

    - run: git config --global user.name "Silverowo"

    # 发布到 GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      run: cd dist
      run: git init
      run: git add .
      run: git commit -m "Deploy"
      run: git push